add_newline = false
command_timeout=10000

[line_break]
disabled = true

[package]
display_private = true

[cmd_duration]
disabled = true

[git_branch]
symbol = "îœ¥ "
truncation_symbol = ""

[battery]
disabled = true

[golang]
symbol = "ï³‘ "
format = "[$symbol($version)]($style) "

[docker_context]
symbol = "ğŸ³"
format = "[$symbol]($style) "
style = "blue bold"
